### ISSUE TITLE
UnhandledPromiseRejectionWarning when building

### ISSUE THREAD

**Issue by MorMundHS-MA** [webpack-contrib/babel-minify-webpack-plugin#69] opened 2017-11-24 17:33 UTC
1. I use the latest Version (v0.2.0).
2. The minimal project is the current(v 1.2.4) [vue webpack template](https://github.com/vuejs-templates/webpack) with this [build config](https://gist.github.com/MorMundHS-MA/3f8536dcdfdc2f75ef1e5c2fecafd45d)

The only changes to the template config file are :
`const MinifyPlugin = require('babel-minify-webpack-plugin')`
and replacing UglifyJs with 
` new MinifyPlugin(),`

When building I get this Error : 
```
$ node build/build.js
(node:23633) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
Done in 18.79s.
```
3. Node version is v6.12.0 on Debian Stretch

**Comment by jamesisaac** [comment] 2017-12-05 12:15
Duplicate of #68

**Comment by evilebottnawi** [comment] 2018-02-02 11:10
Closing because duplicate. Thanks for issue!

**Closed by evilebottnawi** 2018-02-02 11:10 UTC
