### ISSUE TITLE
Doesn't work with draftjs (react)

### ISSUE THREAD

**Issue by pocketjoso** [webpack-contrib/babel-minify-webpack-plugin#57] opened 2017-08-17 13:02 UTC
Hi, wanted to move from uglify to babel-minify, but it breaks draftjs in production, even with the simplest boilerplate code. 

# Setup

`babili-webpack-plugin@0.1.2` - latest at time of speaking
`draft-js@0.10.1` - latest at time of speaking

Webpack:
```js
plugins: [
    new BabiliPlugin({}, {comments: false}),
]
```

`React` code lifted straight from [draft-js docs](https://github.com/facebook/draft-js#using-draftjs):
```js
import React from 'react';
import ReactDOM from 'react-dom';
import {Editor, EditorState} from 'draft-js';

class MyEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state = {editorState: EditorState.createEmpty()};
    this.onChange = (editorState) => this.setState({editorState});
  }
  render() {
    return (
      <Editor editorState={this.state.editorState} onChange={this.onChange} />
    );
  }
}

ReactDOM.render(
  <MyEditor />,
  document.getElementById('container')
);
```

# Output
The code crashes with error below:
![screen shot 2017-08-17 at 14 57 41](https://user-images.githubusercontent.com/7192832/29413375-75b43118-835c-11e7-915b-ba5ede658eed.png)

---
I know this issue report is a bit sparse. I can't get the source maps to work with `babel-minify`, so I can't really tell what's going on. The problem does not appear when using `uglify` instead of babel-minify..

**Comment by michael-ciniawsky** [comment] 2017-08-17 13:34
```js
class MyEditor extends React.Component {
  constructor (props) {
    super(props);
    this.state = { editorState: EditorState.createEmpty() };

    this.onChange.bind(this);
  }

  onChange (editorState) {
     return this.setState({ editorState })
  }

  render () {
    return (
      <Editor editorState={this.state.editorState} onChange={this.onChange} />
    );
  }
}
```

But just a suggestion not 💯

**Comment by pocketjoso** [comment] 2017-08-17 13:56
@michael-ciniawsky well.. yes this is generally how I would write it too, as I said I just copied it from the docs. And should make no difference for this problem?

**Comment by evilebottnawi** [comment] 2017-08-17 14:08
@pocketjoso maybe bug in babel plugins? Can your disable one by one babel plugin to exclude it?

**Comment by michael-ciniawsky** [comment] 2017-08-17 14:16
@pocketjoso Post your current `webpack.config.js` && `.babelrc` then please :).

**Comment by boopathi** [comment] 2017-08-17 15:39
Thanks for reporting.

With the following versions,

```
    "draft-js": "^0.10.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
```

I tried this with latest babel-minify version `0.2.0` and it doesn't throw any errors. I'll close this. Feel free to open the issue in https://github.com/babel/minify if you still have this error as it's a minification error and not related to the webpack plugin.

The latest version of the plugin is not yet published with `0.2.0`. **For now**, with babili-webpack-plugin, you can simply pass, 

**Note: babili-webpack-plugin will be `deprecated`. Updated to `babel-minify-webpack-plugin`.**

in your project

```sh
npm install babel-preset-minify --save-dev
```

and in your config,

```js
new BabiliPlugin({}, {
  babili: require("babel-preset-minify") // babel-preset-minify - version 0.2.0
});
```

**Closed by boopathi** 2017-08-17 15:39 UTC

**Comment by meandmycode** [comment] 2017-08-17 15:51
FWIW @pocketjoso this should be easy to pick apart, already just looking at the stack trace I can see the issue is likely to be somewhere here:

https://github.com/facebook/draft-js/blob/514490b1322e1c123524eae97d4aea25b4da16ce/src/model/immutable/ContentState.js#L210

Since the stack has J, new J then I'm guessing its an issue within Repeat, as it upcasts function calls to constructor calls:

https://github.com/facebook/immutable-js/blob/master/src/Repeat.js

If you enable breakpoint on error you'll probably stop within that function and should be able to work out what went wrong and it should help you see whats going wrong.

**Comment by pocketjoso** [comment] 2017-08-17 17:25
Okay, I found the issue:

I was still running webpack with the `-p` production flag, which for this context seems to yield these two plugins:
```js
new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false
    }),
    new webpack.optimize.UglifyJsPlugin({
      beautify: false,
      mangle: {
        screw_ie8: true,
        keep_fnames: true
      },
      compress: {
        screw_ie8: true
      },
      comments: false
    })
```

So it must have been the combination of `uglify` + `babel-minify` that broken it. Without that flag, it works. Thanks for the help - could perhaps be useful to add as a warning somewhere in docs to remind people to stop using `-p` with `babel-minify`.

**Comment by michael-ciniawsky** [comment] 2017-08-17 18:09
> On a side note, do you know if it makes sense to keep either of the LoaderOptionsPlugin with minimize turned off when using babel-minify-webpack-plugin?

All `p` flag does is set `this.minimize` to `true` (`css-loader`, `html-loader`) and inject `webpack.optimize.UglifyJsPlugin` into the plugins `{Array}`. I discourage it's usage, since an explicit approach in `webpack.config.js` doesn't lead to errors like this

```bash
NODE_ENV="production/development" webpack
```

**webpack.config.js** 
```js
const env = process.env.NODE_ENV
...
{
  loader: 'css-loader'
  options: { minimize: env === 'production' ? true : false }
}
...
plugins: [
  env === 'production' ? new BabiliPlugin() : false
].filter(Boolean) // <= ⚠️ 
```

☝️  `===` `webpack -p` && `LoaderOptionsPlugin({ ...legacy })`, but works with all loaders/plugins and is controlled by the user instead

So for `babel-minify-webpack-plugin` the `-p` has no (direct) effect atm, it could add support for `this.minimize` (`-p`) in case webpack doesn't inject ` UglifyJsPlugin` by default anymore
